from web import db
from web.models import *

db.drop_all()
db.create_all()
user = User("TestUser")
user.save("testpassword")
user = User("tsarkov")
user.save("tsarkov1")
user = User("konnov")
user.save("konnov12")
user = User("mezentsev")
user.save("mezentsev")
user = User("vorobev")
user.save("vorobev1")
user = User("alekseev")
user.save("alekseev")
user = User("semenov")
user.save("semenov1")
user = User("shihanov")
user.save("shihanov")
user = User("dyachek")
user.save("dyachek1")
user = User("kucherov")
user.save("kucherov")
user = User("karimov")
user.save("karimov1")
user = User("valegov")
user.save("valegov1")
user = User("syomochkin")
user.save("syomochkin")
db.session.commit()